// app/layout.tsx
import './globals.css';
import { Inter } from 'next/font/google';
import Header from './header'; // import your header component
import Providers from "./providers";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next.js Dashboard',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
